### ISSUE TITLE
For specific recipients

### ISSUE THREAD

**Issue by bencagri** [gravmatt/js-notify#2]
Hi @gravmatt, thx for this beautiful repo. I see this on [stackoverflow ](http://stackoverflow.com/a/34764143/2185524)

I wonder is it possible to send notifications to recipients. 
Here is an example;
There are two user types.
- Authors
- Editors

When author writes an entry, send notification to editors .
If one of editor approve entry, send notification to author. (Not all of the authors)

Thx.

**Comment by gravmatt** [comment]
@bencagri this is just a wrapper for the Notification object of your browser. No setup needed! Just call the `notify` object and notify-js will handles the rest for you.

So you can call/send notification as you like but just to the user in front of the browser window. It  doesn't matter if the user is a "editor" or "author". 

Notifications are more to get the attention of the user if something happened. For example, if the browser window is not in the foreground. This I guess is the best use case.

I hope I understood you right and this helps 👍

**Comment by bencagri** [comment]
Thx gravmatt. Yes, you understood what I mean.
